[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_and_burn = "v32YSnVQDJfpVZm21APm5V7j1R3xCKU6VbsZRtAXb9A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./provider-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
